
name: CI

on: [push]

jobs:
  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:

    - uses: actions/checkout@v1

    - name: Build
      run: |
        ./build.sh
    - name: Run
      run: |
        ./build/cali

