
# This is a basic workflow from github's template to help you get started with
# Actions

name: cali ci

# Controls when the workflow will run
on:
  push:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    build:
      runs-on: ${{ matrix.os }}

      steps:
        - uses: actions/checkout@v3

        - name: build and run
          run: |
            ./run.sh arg1 arg_two

