
name: cali ci

on: [push]

jobs:
  test:

    name: test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

    - uses: actions/checkout@v1

    - if: matrix.os == 'macos-latest'
      run: |
        brew reinstall gcc

    - if: matrix.os == 'windows-latest'
      name: build only on windows
      run: |
        bash ./build.sh

    - if: matrix.os != 'windows-latest'
      name: build and run
      run: |
        ./run.sh

