
name: cali ci

on: [push]

jobs:
  test:

    name: test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
#    defaults:
#      run:
#        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        #os: [ubuntu-latest, macos-latest]

    steps:

    - uses: actions/checkout@v1

    - if: matrix.os == 'macos-latest'
      run: |
        brew reinstall gcc

    - name: build and run
      run: |
        ./run.sh

